sudo: no
language: node_js
node_js:
- '0.10'

notifications:
    email: false
    irc:
        channels:
            - "irc.mozilla.org#plugincheck"
        on_success: always
        on_failure: always
